// src/pages/TermsOfServicePage.jsx
import { useSEO } from '../hooks/useSEO';

const Section = ({ title, children }) => (
  <div className="mb-8">
    <h2 className="font-semibold text-lg mb-3 text-white">{title}</h2>
    <div className="text-white/50 text-sm leading-relaxed space-y-3">{children}</div>
  </div>
);

export default function TermsOfServicePage() {
  useSEO({ title: 'Terms of Service', description: 'AutoNexus Terms of Service' });

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
      <div className="mb-12">
        <h1 className="font-display text-4xl tracking-wider mb-3">TERMS OF SERVICE</h1>
        <p className="text-white/30 text-sm">Last updated: January 2025</p>
      </div>

      <div className="card p-8">
        <Section title="1. Acceptance of Terms">
          <p>By accessing or using AutoNexus, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.</p>
        </Section>

        <Section title="2. Platform Role">
          <p>AutoNexus is a marketplace platform that connects car buyers with verified dealers. We do not own, sell, or take possession of any vehicles listed on the platform.</p>
          <p>AutoNexus is not a party to any transaction between a buyer and a dealer. We facilitate the connection and provide tools to support the process.</p>
        </Section>

        <Section title="3. Buyer Terms">
          <p>Inquiries sent through AutoNexus are non-binding expressions of interest. Sending an inquiry does not reserve or guarantee availability of a vehicle.</p>
          <p>Deposit payments of 10% are required to reserve a vehicle. This deposit is paid directly to the dealer via bank transfer using the reference number generated by AutoNexus. The remaining balance is settled at the dealership upon pickup.</p>
          <p>AutoNexus is not responsible for disputes arising between buyers and dealers after the initial connection. We encourage buyers to inspect vehicles in person before completing payment.</p>
        </Section>

        <Section title="4. Dealer Terms">
          <p>Dealers must register and maintain an active subscription (KES 5,000/month) to list vehicles on AutoNexus. A 30-day free trial is provided upon registration.</p>
          <p>Dealers are solely responsible for the accuracy, legality, and quality of their listings. Misrepresentation of vehicles is grounds for immediate suspension.</p>
          <p>Dealers must respond to buyer inquiries within 24 hours. Consistent failure to respond may result in suspension of the dealer account.</p>
          <p>AutoNexus reserves the right to suspend or terminate dealer accounts for violations of these terms, fraudulent listings, or non-payment of subscription fees.</p>
        </Section>

        <Section title="5. Subscriptions & Payments">
          <p>Dealer subscriptions are billed monthly at KES 5,000. Subscriptions do not auto-renew — dealers must manually renew before the expiry date.</p>
          <p>Upon subscription expiry, all dealer listings are automatically hidden from buyers until renewal is confirmed by the platform admin.</p>
          <p>Subscription fees are non-refundable except in cases of platform error verified by AutoNexus.</p>
        </Section>

        <Section title="6. AI Features Disclaimer">
          <p>AutoNexus provides AI-powered features including smart search, price prediction, and virtual test drives. These are provided for informational purposes only and do not constitute financial or professional advice.</p>
          <p>Price predictions are estimates based on available market data and should not be solely relied upon for purchasing decisions.</p>
        </Section>

        <Section title="7. Prohibited Conduct">
          <p>Users may not: post fraudulent or misleading listings, use the platform to facilitate illegal transactions, scrape or copy platform data, or attempt to circumvent security measures.</p>
          <p>Violations may result in immediate account termination and potential legal action.</p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>AutoNexus is provided "as is." We make no warranties regarding the accuracy of listings, dealer behavior, or transaction outcomes. Our liability is limited to the amount paid to AutoNexus in the 30 days prior to any claim.</p>
        </Section>

        <Section title="9. Governing Law">
          <p>These terms are governed by the laws of Kenya. Any disputes shall be resolved in the courts of Nairobi, Kenya.</p>
        </Section>

        <Section title="10. Contact">
          <p>For questions about these terms: <strong className="text-white">admin@autonexus.com</strong></p>
        </Section>
      </div>
    </div>
  );
}